source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '7.0'

pod 'AFNetworking', '~> 2.0'
pod 'OBShapedButton'
pod 'Toast', '~> 2.4'
pod 'MRProgress', '~> 0.4.3'
pod 'CocoaSecurity'
pod 'UIAlertView+Blocks'
pod 'UIColor-Hex'
pod 'SWTableViewCell'
pod 'SHPieChartView'
pod 'HACBarChart'
pod 'SHLineGraphView'